<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/1999/xhtml"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Las Bekasi</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            background: #f5f5f5;
            margin: 0;
            padding: 0;
          }
          .wrapper {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
          }
          header {
            background: linear-gradient(135deg, #ff6b35, #f7931e);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
          }
          h1 {
            margin: 0 0 10px 0;
            font-size: 28px;
            font-weight: 600;
          }
          .intro {
            font-size: 14px;
            line-height: 1.6;
            opacity: 0.95;
          }
          .intro a {
            color: white;
            text-decoration: underline;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th {
            background: #f8f9fa;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #dee2e6;
          }
          td {
            padding: 12px;
            border-bottom: 1px solid #dee2e6;
          }
          tr:hover {
            background: #f8f9fa;
          }
          .url {
            color: #ff6b35;
            text-decoration: none;
            word-break: break-all;
          }
          .url:hover {
            text-decoration: underline;
          }
          .stats {
            display: flex;
            gap: 20px;
            margin: 20px 0;
            flex-wrap: wrap;
          }
          .stat-box {
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            padding: 20px;
            border-radius: 8px;
            flex: 1;
            min-width: 200px;
          }
          .stat-number {
            font-size: 32px;
            font-weight: 700;
            margin-bottom: 5px;
          }
          .stat-label {
            font-size: 14px;
            opacity: 0.9;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #dee2e6;
            text-align: center;
            color: #666;
            font-size: 14px;
          }
          .priority-high { color: #28a745; font-weight: 600; }
          .priority-medium { color: #ffc107; font-weight: 600; }
          .priority-low { color: #6c757d; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="wrapper">
          <header>
            <h1>🗺️ XML Sitemap - Las Bekasi</h1>
            <p class="intro">
              This is an XML Sitemap which is supposed to be processed by search engines like Google, Bing, and Yahoo.<br/>
              You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.<br/>
              Generated by Las Bekasi SEO System.
            </p>
          </header>

          <xsl:if test="sitemap:sitemapindex">
            <div class="stats">
              <div class="stat-box">
                <div class="stat-number"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></div>
                <div class="stat-label">Total Sitemaps</div>
              </div>
              <div class="stat-box">
                <div class="stat-number">
                  <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/>
                </div>
                <div class="stat-label">Sitemap Index Files</div>
              </div>
            </div>

            <h2>📂 Sitemap Index</h2>
            <p style="color: #666; margin-bottom: 20px;">This XML Sitemap Index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps</strong>.</p>
            
            <table>
              <thead>
                <tr>
                  <th>Sitemap URL</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}" class="url">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="sitemap:urlset">
            <div class="stats">
              <div class="stat-box">
                <div class="stat-number"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></div>
                <div class="stat-label">Total URLs</div>
              </div>
              <div class="stat-box">
                <div class="stat-number">100%</div>
                <div class="stat-label">Indexed</div>
              </div>
            </div>

            <h2>🔗 URL List</h2>
            <p style="color: #666; margin-bottom: 20px;">This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</strong>.</p>
            
            <table>
              <thead>
                <tr>
                  <th style="width: 50%;">URL</th>
                  <th>Last Modified</th>
                  <th>Change Freq</th>
                  <th>Priority</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}" class="url">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:changefreq"/>
                    </td>
                    <td>
                      <xsl:choose>
                        <xsl:when test="sitemap:priority &gt; 0.8">
                          <span class="priority-high"><xsl:value-of select="sitemap:priority"/></span>
                        </xsl:when>
                        <xsl:when test="sitemap:priority &gt; 0.5">
                          <span class="priority-medium"><xsl:value-of select="sitemap:priority"/></span>
                        </xsl:when>
                        <xsl:otherwise>
                          <span class="priority-low"><xsl:value-of select="sitemap:priority"/></span>
                        </xsl:otherwise>
                      </xsl:choose>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <div class="footer">
            <p>🔥 Generated by <strong>Las Bekasi</strong> - Jasa Las Profesional #1 Sejak 1999</p>
            <p><a href="https://lasbekasi.com" style="color: #ff6b35; text-decoration: none; font-weight: 600;">Visit Las Bekasi Website →</a></p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
